[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/urai-logo-rounded.png"
  description = "The official blog website of URAI"

[params.author]
  name = "URAI"
  email = "contact@urai-group.com"
  image = "img/urai-logo-rounded.png"
  headline = "The official blog website of URAI!"
  bio = "The official blog website of URAI!"
  links = [
    { github = "https://github.com/urai-group" },
    { linkedin = "https://www.linkedin.com/company/109986758/" },
    { mastodon = "https://mastodon.social/@urai" },
    { x-twitter = "https://x.com/urai_group" },
    { instagram = "https://www.instagram.com/urai_group/" },
    { reddit = "https://reddit.com/r/urai" },
    { medium = "https://medium.com/@urai-group" },
  ]
